choice_icon_path = r"static/resources/choice_24dp.svg"
save_icon_path = r"static/resources/save_24dp.svg"
delete_icon_path = r"static/resources/delete_24dp.svg"
graph_icon_path = r"static/resources/graph_24dp.svg"
file_path_icon_path = r"static/resources/file_path_24dp.svg"
report_icon_path = r"static/resources/report_24dp.svg"
sort_icon_path = r"static/resources/sort_24dp.svg"
fullscreen_icon_path = r"static/resources/fullscreen_24dp.svg"

arrow_down_icon_path = r"static/resources/arrow_down_24dp.svg"
main_icon_path = r"static/resources/main_icon.ico"